name: R Package Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - name: Install dependencies
      run: Rscript -e 'install.packages("devtools"); devtools::install_deps(dependencies = TRUE)'
    - name: Build Package
      run: Rscript -e 'devtools::build()'
    - name: Check Package
      run: Rscript -e 'devtools::check()'
